version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/Users/mywo/postgresql/data/
    environment:
      - POSTGRES_USER=hello_fastapi
      - POSTGRES_PASSWORD=hello_fastapi
      - POSTGRES_DB=hello_fastapi_dev
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
